export const blogs = [
    { id: 1, author: { name: "John Doe" }, title: "How to Learn JavaScript", content: "JavaScript is one of the most popular programming languages. In this blog, we will discuss how you can start learning JavaScript efficiently...", publishedDate: "1st Jan 2024" },
    { id: 2, author: { name: "Jane Smith" }, title: "CSS Grid vs Flexbox", content: "CSS Grid and Flexbox are both layout systems in CSS. In this article, we will compare these two systems and help you decide which one to use in different scenarios...", publishedDate: "3rd Jan 2024" },
    { id: 3, author: { name: "Mike Johnson" }, title: "Understanding React Hooks", content: "React Hooks have revolutionized the way we write components in React. In this blog, we will go over the basics of useState, useEffect, and other hooks...", publishedDate: "5th Jan 2024" },
    { id: 4, author: { name: "Sarah Lee" }, title: "Intro to TypeScript", content: "TypeScript is a superset of JavaScript that adds static typing. Learn the basics of TypeScript and how it can improve your development workflow...", publishedDate: "7th Jan 2024" },
    { id: 5, author: { name: "David Kim" }, title: "Best Practices for Writing Clean Code", content: "Writing clean and maintainable code is an essential skill for every developer. This post will provide some best practices to help you write cleaner code...", publishedDate: "9th Jan 2024" },
    { id: 6, author: { name: "Alex Turner" }, title: "JavaScript Array Methods", content: "In this blog post, we will dive into various array methods available in JavaScript like map(), filter(), and reduce(), and how to use them effectively...", publishedDate: "11th Jan 2024" },
    { id: 7, author: { name: "Emily Clark" }, title: "Understanding Asynchronous JavaScript", content: "Asynchronous programming is crucial for handling time-consuming operations like API calls. This post will explain how asynchronous code works in JavaScript...", publishedDate: "13th Jan 2024" },
    { id: 8, author: { name: "Chris Evans" }, title: "CSS Animations: A Beginner's Guide", content: "Learn how to create smooth and eye-catching animations using CSS. This beginner's guide will cover key concepts and examples to get you started...", publishedDate: "15th Jan 2024" },
    { id: 9, author: { name: "Sophia Lee" }, title: "An Introduction to Node.js", content: "Node.js is a powerful JavaScript runtime used for server-side programming. Learn the basics of Node.js and how to create your first server...", publishedDate: "17th Jan 2024" },
    { id: 10, author: { name: "Daniel Miller" }, title: "Top 10 JavaScript Libraries", content: "JavaScript libraries can speed up development and make coding more efficient. In this post, we explore the top 10 most popular JavaScript libraries for 2024...", publishedDate: "19th Jan 2024" },
    { id: 11, author: { name: "Grace Johnson" }, title: "How to Build a Personal Portfolio Website", content: "A personal portfolio website is a great way to showcase your work. This post will guide you through the process of building one from scratch...", publishedDate: "21st Jan 2024" },
    { id: 12, author: { name: "Liam Wilson" }, title: "A Guide to Mobile-First Web Design", content: "Mobile-first web design is an approach where you design for the smallest screen first. Learn how to implement this strategy for responsive websites...", publishedDate: "23rd Jan 2024" },
    { id: 13, author: { name: "Olivia Brown" }, title: "JavaScript ES6 Features You Should Know", content: "ES6 brought many new features to JavaScript. In this post, we will discuss the most important ones, such as arrow functions, destructuring, and promises...", publishedDate: "25th Jan 2024" },
    { id: 14, author: { name: "James Walker" }, title: "SEO for Developers", content: "Search Engine Optimization (SEO) is crucial for getting your website noticed. This article will explain SEO concepts from a developer's perspective...", publishedDate: "27th Jan 2024" },
    { id: 15, author: { name: "Emma Scott" }, title: "React Component Lifecycle Explained", content: "Understanding the React component lifecycle is key to mastering React. This post will walk you through the various lifecycle methods and when to use them...", publishedDate: "29th Jan 2024" },
    { id: 16, author: { name: "William Harris" }, title: "Web Accessibility Best Practices", content: "Ensuring your website is accessible to everyone is essential. This article provides best practices to follow when building accessible websites...", publishedDate: "31st Jan 2024" },
    { id: 17, author: { name: "Charlotte Davis" }, title: "Exploring CSS Variables", content: "CSS Variables are a powerful feature that allows you to reuse values throughout your stylesheet. This post explains how to use them and why they are useful...", publishedDate: "2nd Feb 2024" },
    { id: 18, author: { name: "Lucas Miller" }, title: "Building a REST API with Express", content: "Express.js is a web application framework for Node.js. In this post, we'll show you how to build a simple REST API using Express...", publishedDate: "4th Feb 2024" },
    { id: 19, author: { name: "Mia Moore" }, title: "How to Handle Errors in JavaScript", content: "Error handling is crucial in any application. This blog post will cover the best ways to handle errors in JavaScript, including try/catch and custom error handling...", publishedDate: "6th Feb 2024" },
    { id: 20, author: { name: "Aiden Clark" }, title: "Introduction to Vue.js", content: "Vue.js is a progressive JavaScript framework used for building user interfaces. Learn the basics of Vue.js and how to create your first app...", publishedDate: "8th Feb 2024" }
  ];
  