name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNGVjYTExZjctODVlMy00NzYxLWEyNDItZTVkNTdhYTBiYmIzIiwidGVuYW50X2lkIjoiM2ZhMWIwZjE5YmIwZGNmYjQ3ZWE2ZjYyMTNkODkzZWJlMzgzNTRlNzYxMjkzN2IxZTgwNTllOWI2MzU2YWRhOCIsImludGVybmFsX3NlY3JldCI6IjQ5NDI3ZjhhLWZhN2QtNGRlNi04MGNjLWU1M2RjZDcxM2FjNyJ9.aKwU5CIxhHJWUuGO95vBVXdgKuxWPw2suZ8Mx4UOiSc"
JWT_SECRET = "varunpjpsecret"