export const blogImageSrcs = [
  "https://media.gettyimages.com/id/183851840/photo/bad-repair-pothole-in-road-t-junction-suffers-frost-damage.webp?s=2048x2048&w=gi&k=20&c=wrxr6GzScn0COhcV_06-NsczyXTIEfo64Fv-v0lUp-Y=",
  "https://www.pixelstalk.net/wp-content/uploads/image12/Minimalist-forest-lake-reflection-with-tall-trees-and-a-tranquil.jpg",
  "https://www.pixelstalk.net/wp-content/uploads/image12/A-full-moon-illuminating-a-calm-starry-night-sky-over-a-serene-ocean-with-soft-reflections-on-the-water.jpg",
  "https://www.pixelstalk.net/wp-content/uploads/image12/A-rainbow-over-a-waterfall-with-mist-and-sunlight-creating-a-magical-atmosphere.jpg",
  "https://media.gettyimages.com/id/1921523386/vector/vibrant-bright-blotched-empty-blank-smudged-red-grunge-textured-effect-painted-rustic-wall.webp?s=1024x1024&w=gi&k=20&c=2OBcoZ4DbhDWrpjoTP3clSjyJKwSJU5Atm6PxOsoufo=",
  "https://www.pixelstalk.net/wp-content/uploads/image12/A-beach-1080p-Full-HD-Image-with-a-lighthouse-standing-tall-on-a-rocky-promontory.jpg",
  "https://media.gettyimages.com/id/166357772/photo/dark-forest-trail.webp?s=1024x1024&w=gi&k=20&c=qYh2sFNR4deHr3W3lfMYA0XXpEocJigTtRRDUWCwGhg="
];

export const blogs = [
  {
    blogId: "1",
    author: { name: "Alice Johnson" },
    imageSrc: "https://media.gettyimages.com/id/183851840/photo/bad-repair-pothole-in-road-t-junction-suffers-frost-damage.webp?s=2048x2048&w=gi&k=20&c=wrxr6GzScn0COhcV_06-NsczyXTIEfo64Fv-v0lUp-Y=",
    title: "Exploring the Mountains",
    subtitle: "A journey through rocky paths",
    content: "The mountains stood tall, majestic and unwavering. We packed our bags, laced up our boots, and embraced the challenge ahead...",
    publishedDate: "2025-06-22T10:00:00Z",
    claps: 120,
  },
  {
    blogId: "2",
    author: { name: "Bob Smith" },
    imageSrc: "https://www.pixelstalk.net/wp-content/uploads/image12/Minimalist-forest-lake-reflection-with-tall-trees-and-a-tranquil.jpg",
    title: "The Art of Minimalism",
    subtitle: "Living with less and loving it",
    content: "Minimalism isn't just about having fewer things—it's about finding joy in simplicity and purpose in everything you keep...",
    publishedDate: "2025-06-21T09:30:00Z",
    claps: 95,
  },
  {
    blogId: "3",
    author: { name: "Carol Lee" },
    imageSrc: "https://www.pixelstalk.net/wp-content/uploads/image12/A-full-moon-illuminating-a-calm-starry-night-sky-over-a-serene-ocean-with-soft-reflections-on-the-water.jpg",
    title: "Mastering JavaScript",
    subtitle: "Tips for writing clean and effective code",
    content: "JavaScript offers a powerful set of tools—but it’s only effective when your code is readable, reusable, and maintainable...",
    publishedDate: "2025-06-20T08:15:00Z",
    claps: 210,
  },
  {
    blogId: "4",
    author: { name: "" },
    imageSrc: "https://www.pixelstalk.net/wp-content/uploads/image12/A-rainbow-over-a-waterfall-with-mist-and-sunlight-creating-a-magical-atmosphere.jpg",
    title: "City Life vs Country Life",
    subtitle: "Where does your heart belong?",
    content: "While city life is fast-paced and exciting, country life brings peace, quiet, and a closer connection to nature...",
    publishedDate: "2025-06-19T11:45:00Z",
    claps: 76,
  },
  {
    blogId: "5",
    author: { name: "Daniel Cho" },
    imageSrc: "https://media.gettyimages.com/id/1921523386/vector/vibrant-bright-blotched-empty-blank-smudged-red-grunge-textured-effect-painted-rustic-wall.webp?s=1024x1024&w=gi&k=20&c=2OBcoZ4DbhDWrpjoTP3clSjyJKwSJU5Atm6PxOsoufo=",
    title: "Healthy Habits for Developers",
    subtitle: "Balancing code with wellness",
    content: "Sitting all day isn’t ideal. Here’s how you can move more, stress less, and build healthy habits in your dev workflow...",
    publishedDate: "2025-06-18T14:00:00Z",
    claps: 188,
  },
  {
    blogId: "6",
    author: { name: "Emily Carter" },
    imageSrc: "https://www.pixelstalk.net/wp-content/uploads/image12/A-beach-1080p-Full-HD-Image-with-a-lighthouse-standing-tall-on-a-rocky-promontory.jpg",
    title: "A Beginner’s Guide to React",
    subtitle: "Understanding components, props, and state",
    content: "React makes UI development smooth once you get the hang of its component-based model...",
    publishedDate: "2025-06-17T13:00:00Z",
    claps: 133,
  },
  {
    blogId: "7",
    author: { name: "Frank Zhang" },
    imageSrc: "https://media.gettyimages.com/id/166357772/photo/dark-forest-trail.webp?s=1024x1024&w=gi&k=20&c=qYh2sFNR4deHr3W3lfMYA0XXpEocJigTtRRDUWCwGhg=",
    title: "Top 5 Coding Interview Mistakes",
    subtitle: "And how to avoid them",
    content: "Preparing for coding interviews? Don’t fall into these common traps...",
    publishedDate: "2025-06-16T11:30:00Z",
    claps: 245,
  },
  {
    blogId: "8",
    author: { name: "" },
    title: "Working Remotely: Pros & Cons",
    subtitle: "What I learned after 2 years of remote work",
    content: "Remote work can be freeing, but it's not for everyone. Here's my experience...",
    publishedDate: "2025-06-15T09:45:00Z",
    claps: 67,
  },
  {
    blogId: "9",
    author: { name: "Grace Liu" },
    title: "The Rise of AI in Daily Life",
    subtitle: "How smart tech is changing our routines",
    content: "From smart assistants to recommendation systems, AI is everywhere...",
    publishedDate: "2025-06-14T08:20:00Z",
    claps: 302,
  },
  {
    blogId: "10",
    author: { name: "Henry Patel" },
    title: "Investing 101 for Techies",
    subtitle: "How to make your money work for you",
    content: "You spend hours coding. Now let your money grow with some smart investing strategies...",
    publishedDate: "2025-06-13T12:10:00Z",
    claps: 143,
  },
  {
    blogId: "11",
    author: { name: "Isabel Green" },
    title: "How I Built My First App",
    subtitle: "A journey from idea to App Store",
    content: "Building an app felt intimidating at first, but breaking it into small steps helped me stay on track...",
    publishedDate: "2025-06-12T10:00:00Z",
    claps: 198,
  },
  {
    blogId: "12",
    author: { name: "Jake Rogers" },
    title: "Understanding CSS Grid",
    subtitle: "The layout system you didn't know you needed",
    content: "CSS Grid is a powerful layout system that can handle even the most complex designs...",
    publishedDate: "2025-06-11T09:00:00Z",
    claps: 121,
  },
  {
    blogId: "13",
    author: { name: "Kara Singh" },
    title: "What Makes a Great Team?",
    subtitle: "Lessons from remote collaboration",
    content: "Trust, communication, and shared goals—these are the pillars of any strong dev team...",
    publishedDate: "2025-06-10T13:30:00Z",
    claps: 159,
  },
  {
    blogId: "14",
    author: { name: "" },
    title: "Why I Switched to Linux",
    subtitle: "Leaving macOS and Windows behind",
    content: "Linux gives you control, power, and community support like nothing else...",
    publishedDate: "2025-06-09T15:00:00Z",
    claps: 88,
  },
  {
    blogId: "15",
    author: { name: "Liam Murphy" },
    title: "Photography Tips for Travelers",
    subtitle: "Capture the world through your lens",
    content: "Travel photography is about more than pretty pictures—it's about storytelling...",
    publishedDate: "2025-06-08T10:20:00Z",
    claps: 94,
  },
  {
    blogId: "16",
    author: { name: "Maria Gomez" },
    title: "How to Beat Burnout",
    subtitle: "Surviving the hustle without breaking down",
    content: "Burnout is real, but recovery is possible. Here’s what worked for me...",
    publishedDate: "2025-06-07T08:10:00Z",
    claps: 233,
  },
  {
    blogId: "17",
    author: { name: "Noah Wright" },
    title: "Is TypeScript Worth It?",
    subtitle: "A JavaScript developer’s take",
    content: "TypeScript adds type safety and helps large codebases stay sane...",
    publishedDate: "2025-06-06T11:45:00Z",
    claps: 178,
  },
  {
    blogId: "18",
    author: { name: "Olivia Ray" },
    title: "UX Principles Every Dev Should Know",
    subtitle: "Making apps usable, not just functional",
    content: "Good UX turns a good product into a great experience...",
    publishedDate: "2025-06-05T14:30:00Z",
    claps: 205,
  },
  {
    blogId: "19",
    author: { name: "Patrick Doyle" },
    title: "Debugging Like a Pro",
    subtitle: "How to fix bugs efficiently and calmly",
    content: "Debugging isn't just trial and error. It's an art form...",
    publishedDate: "2025-06-04T16:00:00Z",
    claps: 132,
  },
  {
    blogId: "20",
    author: { name: "" },
    title: "How to Write Better Documentation",
    subtitle: "Docs that your future self will thank you for",
    content: "Documentation is just as important as your code. Here's how to do it right...",
    publishedDate: "2025-06-03T09:50:00Z",
    claps: 111,
  },
];

export default blogs;
